export default [
  'Vamonos a Junkyard',
  'A Stadium en chinga',
  'Fuga al Hospital',
  'Amonos a la Base Militar',
  'A la Carcel, ¿SOMOS HOMBRES O PUTOS?',
  'Jalados a TV Station',
  'Jalense a Downtown',
  'Nos chingamos al Aeropuerto',
  'A Promenade Este, prros',
  'Promenade Oeste, jodidos',
  'A BONEYARD A LA VERGAA',
  'Ni modo, a Gora',
  'Lumber Yard, amonos',
  'Fuga al Ikea, (Superstore), pinche indio jodido',
  'Amonos a AburriLandia',
];
